Traceback (most recent call last):
  File "/home/robot/src/calibrate.py", line 31, in <module>
    compass = CompassSensor(INPUT_4)
  File "/home/robot/src/calibrate.py", line 12, in __init__
    super().__init__(driver_name="ht-nxt-compass", address=address, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 78, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 223, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 54, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: CompassSensor(ev3-ports:in4) is not connected.
