Traceback (most recent call last):
  File "/home/robot/src/retry.py", line 270, in <module>
    robot = Robot()
  File "/home/robot/src/retry.py", line 34, in __init__
    self.compass_sensor = CompassSensor(driver_name="ht-nxt-compass", address=INPUT_2)
  File "/home/robot/src/retry.py", line 23, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 78, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 223, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 54, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: CompassSensor(ev3-ports:in2) is not connected.
